langauge: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t harshakalva/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true harshakalva/react-test npm test

after_success:
    - docker build -t harshakalva/multi-client ./client
    - docker build -t harshakalva/multi-nginx ./nginx
    - docker build -t harshakalva/multi-server ./server
    - docker build -t harshakalva/multi-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push  harshakalva/multi-client
    - docker push  harshakalva/multi-nginx
    - docker push  harshakalva/multi-server
    - docker push  harshakalva/multi-worker

deploy :
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker2
    env: MultiDocker2-env
    bucket_name: elasticbeanstalk-us-east-1-267479437291
    bucket_path: docker-multi
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

